### ISSUE TITLE
单独显示，收起 崩溃

### ISSUE THREAD

**Issue by spring-z** [huanghaibin-dev/CalendarView#112]
```

Process: tech.lastline.calendar, PID: 12109
                                                                        java.lang.NullPointerException: Attempt to invoke virtual method 'float android.view.ViewGroup.getTranslationY()' on a null object reference
                                                                            at com.haibin.calendarview.CalendarLayout.shrink(CalendarLayout.java:422)
                                                                            at tech.lastline.calendar.MainActivity.isShow(MainActivity.java:37)
                                                                            at tech.lastline.calendar.MainActivity.lambda$onCreate$0$MainActivity(MainActivity.java:32)
                                                                            at tech.lastline.calendar.MainActivity$$Lambda$0.onClick(Unknown Source:0)
                                                                            at android.view.View.performClick(View.java:6294)
                                                                            at android.view.View$PerformClick.run(View.java:24770)
                                                                            at android.os.Handler.handleCallback(Handler.java:790)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                            at android.os.Looper.loop(Looper.java:164)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

```

**Comment by spring-z** [comment]
```
<?xml version="1.0" encoding="utf-8"?><!--suppress ALL -->
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    tools:context=".MainActivity">

    <Button
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:id="@+id/button"/>

    <com.haibin.calendarview.CalendarLayout
        android:id="@+id/calendarLayout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="#fff"
        android:orientation="vertical"
        app:calendar_content_view_id="@+id/nestedScrollView"
        app:default_status="expand">

        <com.haibin.calendarview.CalendarView
            android:id="@+id/calendarView"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:month_view_show_mode="mode_only_current"/>

    </com.haibin.calendarview.CalendarLayout>


</LinearLayout>

```

**Comment by spring-z** [comment]
```
Button button = findViewById(R.id.button);

        button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (calendarLayout.isExpand()){
                    calendarLayout.shrink();
                }else {
                    calendarLayout.expand();
                }
            }
        });
```

**Comment by huanghaibin-dev** [comment]
你不需要收缩功能，不要用CalendarLayout，而且你指定了app:calendar_content_view_id="@+id/nestedScrollView"，这个也不存在

**Comment by spring-z** [comment]
看到了，不是不需要这个，是要做一个点击弹出月份的功能，默认进入是周

**Comment by spring-z** [comment]
有什么实现的方案吗？进入是缩起的周视图，点击显示全部月视图

**Comment by huanghaibin-dev** [comment]
你需要指定一个View

**Comment by spring-z** [comment]
```
<com.haibin.calendarview.CalendarLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:calendar_show_mode="both_month_week_view"
        android:id="@+id/calendarLayout"
        app:default_status="shrink"
        app:calendar_content_view_id="@+id/nestedScrollView">

        <com.haibin.calendarview.CalendarView
            android:id="@+id/calendarView"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            app:month_view_show_mode="mode_only_current"/>

        <android.support.v4.widget.NestedScrollView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:id="@+id/nestedScrollView">

        </android.support.v4.widget.NestedScrollView>



    </com.haibin.calendarview.CalendarLayout>
```

这样就可以了，谢谢
