### ISSUE TITLE
Monkey 测试报 ArithmeticException 错误

### ISSUE THREAD

**Issue by 13568810905** [huanghaibin-dev/CalendarView#419]
在云测中进行Monkey测试，执行了88款机型，11个机型没通过测试，其中6款机型日志记录的错误为 `java.lang.ArithmeticException,divide by zero`

详细日志如下
```
java.lang.ArithmeticException: divide by zero
    at com.haibin.calendarview.BaseMonthView.getIndex(BaseMonthView.java:116)
    at com.haibin.calendarview.MonthView.onClick(MonthView.java:105)
    at android.view.View.performClick(View.java:5184)
    at android.view.View$PerformClick.run(View.java:20910)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:145)
    at android.app.ActivityThread.main(ActivityThread.java:5942)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```
![image](https://user-images.githubusercontent.com/34223095/55024349-a1d59d80-5039-11e9-8166-f8f165e28dfb.png)

**Comment by huanghaibin-dev** [comment]
已经修复了，抱歉，现在jcenter除了问题发的版本用不了，建议直接导入module使用了

**Comment by 13568810905** [comment]
更新到2.5.8后没有问题了
