### ISSUE TITLE
Attempt to read from field &#39;com.haibin.calendarview.CalendarView$OnViewChangeListener 

### ISSUE THREAD

**Issue by yixinyuan** [huanghaibin-dev/CalendarView#532]
大神，瞅瞅这个问题怎么回事？友盟统计上统计到的，这个异常还挺多。

java.lang.NullPointerException: Attempt to read from field &#39;com.haibin.calendarview.CalendarView$OnViewChangeListener com.haibin.calendarview.CalendarViewDelegate.mViewChangeListener&#39; on a null object reference
	at com.haibin.calendarview.CalendarLayout.onShowWeekView(CalendarLayout.java:797)
	at com.haibin.calendarview.CalendarLayout.showWeek(CalendarLayout.java:784)
	at com.haibin.calendarview.CalendarLayout.access$700(CalendarLayout.java:47)
	at com.haibin.calendarview.CalendarLayout$6.onAnimationEnd(CalendarLayout.java:710)
	at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1239)
	at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:766)
	at android.animation.ValueAnimator$AnimationHandler$1.run(ValueAnimator.java:801)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:862)
	at android.view.Choreographer.doCallbacks(Choreographer.java:674)
	at android.view.Choreographer.doFrame(Choreographer.java:607)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:848)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:179)
	at android.app.ActivityThread.main(ActivityThread.java:5769)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)

**Comment by huanghaibin-dev** [comment]
什么版本有这个问题？

**Comment by huanghaibin-dev** [comment]
这个问题是几个版本之前的问题，新版本已经修复了，应该是monkey测试操作速度很快造成的，这个方法是动画结束调用，界面关闭导致的

**Comment by yixinyuan** [comment]
好的，那我更新下版本

**Comment by yixinyuan** [comment]
> 这个问题是几个版本之前的问题，新版本已经修复了，应该是猴子测试操作速度很快造成的，这个方法是动画结束调用，界面关闭导致的

感谢大神，那我更新下版本

**Comment by yixinyuan** [comment]
> 版本

现在用的版本是3.5.9

**Comment by ZhangHaoChase** [comment]
最新版本在小米14上面还会出现这个问题呢
