### ISSUE TITLE
软件运行时崩溃，无法显示界面

### ISSUE THREAD

**Issue by sprikid** [huanghaibin-dev/CalendarView#550]
下面是崩溃前的提示信息：
--------- beginning of crash
09-19 11:47:32.466 29913-29913/cn.mahus.mhstudymonitor E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cn.mahus.mhstudymonitor, PID: 29913
    android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class com.haibin.calendarview.CalendarView
        at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at cn.mahus.mhstudymonitor.FragmentRecordCalendar.onCreateView(FragmentRecordCalendar.java:24)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2439)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:764)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
     Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class com.haibin.calendarview.CalendarView
        at android.view.LayoutInflater.createView(LayoutInflater.java:645)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
        at cn.mahus.mhstudymonitor.FragmentRecordCalendar.onCreateView(FragmentRecordCalendar.java:24) 
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2439) 
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460) 
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784) 
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852) 
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802) 
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625) 
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411) 
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366) 
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273) 
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:764) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at android.view.LayoutInflater.createView(LayoutInflater.java:619)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
        at cn.mahus.mhstudymonitor.FragmentRecordCalendar.onCreateView(FragmentRecordCalendar.java:24) 
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2439) 
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460) 
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784) 
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852) 
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802) 
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625) 
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411) 
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366) 
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273) 
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:764) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626) 
     Caused by: android.view.InflateException: Binary XML file line #15: Binary XML file line #15: Error inflating class com.haibin.calendarview.MonthViewPager
        at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at com.haibin.calendarview.CalendarView.init(CalendarView.java:99)
        at com.haibin.calendarview.CalendarView.<init>(CalendarView.java:90)
        at java.lang.reflect.Constructor.newInstance(Native Method) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:619) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
        at cn.mahus.mhstudymonitor.FragmentRecordCalendar.onCreateView(FragmentRecordCalendar.java:24) 
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2439) 
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460) 
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784) 
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852) 
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802) 
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625) 
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411) 
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366) 
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273) 
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:764) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626) 
     Caused by: android.view.InflateException: Binary XML file line #15: Error inflating class com.haibin.calendarview.MonthViewPager
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
        at com.haibin.calendarview.CalendarView.init(CalendarView.java:99) 
        at com.haibin.calendarview.CalendarView.<init>(CalendarView.java:90) 
        at java.lang.reflect.Constructor.newInstance(Native Method) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:619) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
        at cn.mahus.mhstudymonitor.FragmentRecordCalendar.onCreateView(FragmentRecordCalendar.java:24) 
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2439) 
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460) 
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784) 
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852) 
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802) 
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625) 
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411) 
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366) 
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273) 
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:764) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.haibin.calendarview.MonthViewPager" on path: DexPathList[[zip file "/data/app/cn.mahus.mhstudymonitor-2/base.apk", zip file "/data/app/cn.mahus.mhstudymonitor-2/split_lib_dependencies_apk.apk", zip file "/data/app/cn.mahus.mhstudymonitor-2/split_lib_slice_0_apk.apk", zip file "/data/app/cn.mahus.mhstudymonitor-2/split_lib_slice_1_apk.apk", zip file "/data/app/cn.mahus.mhstudymonitor-2/split_lib_slice_2_apk.apk", zip file "/data/app/cn.mahus.mhstudymonitor-2/split_lib_slice_3_apk.apk", zip 
09-19 11:47:32.470 4603-4615/? W/ActivityManager:   Force finishing activity cn.mahus.mhstudymonitor/.MainActivity
09-19 11:47:32.504 7948-8005/? I/DataMinerService: {
        "AppCrashes": "0",
        "StackTrace": "android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class com.haibin.calendarview.CalendarView\n\tat android.view.LayoutInflater.inflate(LayoutInflater.java:539)\n\tat android.view.LayoutInflater.inflate(LayoutInflater.java:423)\n\tat cn.mahus.mhstudymonitor.FragmentRecordCalendar.onCreateView(FragmentRecordCalendar.java:24)\n\tat android.support.v4.app.Fragment.performCreateView(Fragment.java:2439)\n\tat android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)",
        "Package": "cn.mahus.mhstudymonitor",
        "VersionName": "1.0",
        "VersionCode": "1",
        "appname": "com_blackberry_dm",
        "appversion": "1.0",
        "eventid": "onStructuredEvent",
        "action": "crashed",
        "category": "application",
        "eventDesc": "onApplicationCrashed"
    }

使用的AndroidStudio，在app.gradle中增加了
implementation 'com.haibin:calendarview:3.6.7'
layout文件配置如下
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:orientation="vertical">

        <com.haibin.calendarview.CalendarView
            android:id="@+id/calendarview"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="#fff"
            app:calendar_padding="10dp"
            app:current_month_text_color="#333333"
            app:current_month_lunar_text_color="#CFCFCF"
            app:other_month_text_color="#e1e1e1"
            app:other_month_lunar_text_color="#e1e1e1"
            app:scheme_text_color="#333"
            app:scheme_theme_color="#128c4b"
            app:selected_lunar_text_color="#CFCFCF"
            app:month_view="cn.mahus.mhstudymonitor.MeiZuMonthView"
            app:selected_text_color="#333"
            app:selected_theme_color="#80cfcfcf"
            app:week_background="#fff"
            app:week_text_color="#111111"
            app:week_start_with="sun"
            app:week_view_scrollable="true"
            app:year_view_day_text_color="#333333"
            app:year_view_day_text_size="9sp"
            app:year_view_month_text_color="#ff0000"
            app:year_view_month_text_size="20sp"
            app:month_view_show_mode="mode_only_current"
            app:year_view_scheme_color="#f17706"/>

    <TextView
        android:id="@+id/info"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="10:00-22:00"
        android:textAlignment="center"
        android:visibility="gone" />

    <Button
        android:id="@+id/view"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="查看"
        android:visibility="gone" />

</LinearLayout>

**Comment by huanghaibin-dev** [comment]
区分一下Androidx版本和support即可，如果你项目用的是support的，用3.6.6版本

**Comment by sprikid** [comment]
改为3.6.6版本好了，谢谢

**Comment by sprikid** [comment]
谢谢

**Comment by pdthoan174** [comment]
You should set isMinifyEnabled = false or config ProGuard file like that:
-keepattributes Signature
-keep class com.packagename.example.{your package contain custom calendar view}.** { *; }
