### ISSUE TITLE
有个新bug：IndexOutOfBoundsException 

### ISSUE THREAD

**Issue by yaoxin2017** [huanghaibin-dev/CalendarView#7]
在4.4系统上点击几次就会出现这个bug：IndexOutOfBoundsException ，在安卓7.0系统上多次快速点击也会出现。
error log：
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{422a0048 position=2 id=-1, oldPos=-1, pLpos:-1 scrap [attachedScrap] tmpDetached no parent}
                                                                                  at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5297)

**Comment by yaoxin2017** [comment]
测试机器是 华为平板 4.4 系统    三星s7 7.0系统

**Comment by yaoxin2017** [comment]
补充  在点击日期的时候

**Comment by huanghaibin-dev** [comment]
@yaoxin2017 你好，请问是最新1.0.6版本吗？

**Comment by yaoxin2017** [comment]
用的是1.0.4  
我百度一下 有个解决方法

**Comment by yaoxin2017** [comment]
你看看
http://blog.csdn.net/lovexieyuan520/article/details/50537846

**Comment by yaoxin2017** [comment]
对了 1.0.6相比1.0.4增加了什么新功能，我因为要解决横屏的问题  所以我没有使用依赖方式 是直接下载源码修改后使用的

**Comment by yaoxin2017** [comment]
我使用4.4模拟器  多次点击也会出现这个问题  ，但是华为平板几乎点不了5次就会出现这个问题，三星7.0不容易报错  但是存在这个问题！
我试过了上面连接的解决方法 ，那个try catch方法 好像仍然会报错  ：
/AndroidRuntime: FATAL EXCEPTION: main
                                                                                Process: com.feidi.supervisionEducation, PID: 23118
                                                                                java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{4242bcb0 position=2 id=-1, oldPos=-1, pLpos:-1 scrap [attachedScrap] tmpDetached no parent}
                                                                                    at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5297)
                                                                                    at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5479)
                                                                                    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
                                                                                    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
                                                                                    at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
                                                                                    at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
                                                                                    at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                                                                    at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
                                                                                    at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
                                                                                    at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
                                                                                    at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
                                                                                    at android.view.View.layout(View.java:14876)

**Comment by yaoxin2017** [comment]
我下午自己测试  好像是 我自己修改后增加的bug  因为log不是很清楚  所以我以为是你的代码报的错  不好意思啊  不过万一以后出现这个问题  这个也可以给后来者一个提示

**Comment by huanghaibin-dev** [comment]
@yaoxin2017 1.0.6新增节假日这些功能

**Comment by huanghaibin-dev** [comment]
全新版本已经开源，可以任意自定义UI了，谢谢支持。
