### ISSUE TITLE
java.lang.RuntimeException: Unable to start activity ComponentInfo android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class com.haibin.calendarview.CalendarView

### ISSUE THREAD

**Issue by sranjith096** [huanghaibin-dev/CalendarView#86]
Exception occurs at `SetContentView()` in Activity Class. Couldn't figure out what the issue is. I used the same layout as used in the demo app.

> 02-14 14:28:55.085 2983-2983/co.example.app E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: co.example.app, PID: 2983
                                                                      java.lang.RuntimeException: Unable to start activity ComponentInfo{co.example.app/co.example.app.ui.schedule.ScheduleActivity}: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class com.haibin.calendarview.CalendarView
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2585)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2667)
                                                                          at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1494)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                          at android.os.Looper.loop(Looper.java:207)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5776)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
                                                                       Caused by: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class com.haibin.calendarview.CalendarView
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                          at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
                                                                          at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                                          at co.example.app.ui.schedule.ScheduleActivity.onCreate(ScheduleActivity.java:48)
                                                                          at android.app.Activity.performCreate(Activity.java:6582)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2532)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2667) 
                                                                          at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1494) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                          at android.os.Looper.loop(Looper.java:207) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5776) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679) 
                                                                       Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class com.haibin.calendarview.CalendarView
                                                                          at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
                                                                          at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
                                                                          at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                          at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
                                                                          at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                                          at co.example.app.ui.schedule.ScheduleActivity.onCreate(ScheduleActivity.java:48) 
                                                                          at android.app.Activity.performCreate(Activity.java:6582) 
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113) 
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2532) 
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2667) 
                                                                          at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1494) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                          at android.os.Looper.loop(Looper.java:207) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5776) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679) 
                                                                       Caused by: java.lang.reflect.InvocationTargetException
                                                                          at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                          at android.view.LayoutInflater.createView(LayoutInflater.java:619)
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                                          at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) 
                                                                          at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                          at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
                                                                          at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                                          at co.example.app.ui.schedule.ScheduleActivity.onCreate(ScheduleActivity.java:48) 
                                                                          at android.app.Activity.performCreate(Activity.java:6582) 
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113) 
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2532) 
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2667) 
                                                                          at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1494) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                          at android.os.Looper.loop(Looper.java:207) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5776) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679) 
                                                                       Caused by: java.lang.IllegalArgumentException: Cannot add a null child view to a ViewGroup
                                                                          at android.view.ViewGroup.addView(ViewGroup.java:4206)
                                                                          at com.haibin.calendarview.CalendarView.init(CalendarView.java:110)
                                                                          at com.haibin.calendarview.CalendarView.<init>(CalendarView.java:84)
                                                                          at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                          at android.view.LayoutInflater.createView(LayoutInflater.java:619) 
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                                          at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) 
                                                                          at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                          at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
                                                                          at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
                                                                          at co.example.app.ui.schedule.ScheduleActivity.onCreate(ScheduleActivity.java:48) 
                                                                          at android.app.Activity.performCreate(Activity.java:6582) 
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113) 
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2532) 
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2667) 
                                                                          at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1494) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                                          at android.os.Looper.loop(Looper.java:207) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5776) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

**Comment by HYTCTony** [comment]
我也是这个问题，求作者帮忙解决。

**Comment by huanghaibin-dev** [comment]
v4或者v7包冲突了，使用exclude排除一下

**Comment by HYTCTony** [comment]
源码直接复制到主项目里面，不存在冲突吧？

**Comment by huanghaibin-dev** [comment]
直接copy源码也会吗？很多人使用都没问题啊

**Comment by huanghaibin-dev** [comment]
可以加QQ：1505651581看看什么问题

**Comment by nan403** [comment]
原因找到了吗 我也遇到一个相同的问题

**Comment by huanghaibin-dev** [comment]
自定义的路径对了就没问题，不要照搬README的啊

**Comment by nan403** [comment]
好的谢谢了，我之前是用dependencies引入的，现在把源码导入进去了，也遇到路径的问题，主要是问题不好定位，现在已经解决了

**Comment by timfei** [comment]
@nan403 你好，请问是如何解决的？没明白上面说的自定义的路径的说明
我是这样添加的
implementation('com.haibin:calendarview:3.6.4') {
        exclude module: 'support-v4'
        exclude group: 'com.android.support'
 }
谢谢

**Comment by HYTCTony** [comment]
请按包名修改自定义view的路径

**Comment by timfei** [comment]
@HYTCTony 嗯嗯，谢谢
